deepseek:
  api-key: sk-8160be89fcea4fc985ef6c923e2385c0
  base-url: https://api.deepseek.com

qdrant:
  host: localhost
  port: 16333
  doc-collection: aiknowledge-doc

ollama:
  host: localhost
  port: 11434
  model: nomic-embed-text

meilisearch:
  host: localhost
  port: 7700

server:
  port: 8081
